name: test-callee
on:
  workflow_call:
    inputs:
      push-image:
        type: boolean
        default: false
    secrets:
      GHCR_TOKEN:
        required: false
jobs:
  probe:
    runs-on: [self-hosted, linux, x64, tainan-node05]
    steps:
      - run: echo probe
  image:
    if: inputs.push-image
    needs: probe
    runs-on: [self-hosted, linux, x64, tainan-node05]
    steps:
      - run: echo no-permissions
